name: CI / "Storyteller UI" app
on:
  # Doc on issue_comment event: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only
  issue_comment:
    types: [created, edited]

jobs:
  test_coverage_on_request:
    name: Test coverage
    if: ${{ github.event.issue.pull_request }}
    strategy:
      matrix:
        node: ["18"]

    runs-on: ubuntu-20.04

    steps:
#      # TODO: Need to review the code in this project, and see if we can
#      #   implement emojifying the source comment for the GHA run
#      #   without sending a GitHub token out to a third-party service.
#      # https://github.com/actions-cool/emoji-helper
#      - name: ACK comment
#        uses: actions-cool/emoji-helper@v1
#        with:
#          github_token: ${{ github.token }}
#          comment_id: ${{ github.event.comment.id }}
#          emoji: eyes

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup workflow variables
        id: workflow-vars
        shell: bash
        env:
          GITHUB_FEATURE_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "sha=${GITHUB_FEATURE_SHA}" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Check Github SHA & Branch
        run: |
          echo "SHA: ${{ steps.workflow-vars.outputs.sha }}"
          echo "BRANCH: ${{ steps.workflow-vars.outputs.branch }}"
          echo "GITHUB REF: ${GITHUB_REF}"

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        if: ${{ contains(github.event.comment.body, '/coverage') }}
        run: npm test -- --ci --coverage

  deploy_on_request:
    name: Deploy for review
    if: ${{ github.event.issue.pull_request }}
    strategy:
      matrix:
        node: ["18"]

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup workflow variables
        id: workflow-vars
        shell: bash
        env:
          GITHUB_FEATURE_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "sha=${GITHUB_FEATURE_SHA}" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Check Github SHA & Branch
        run: |
          echo "SHA: ${{ steps.workflow-vars.outputs.sha }}"
          echo "BRANCH: ${{ steps.workflow-vars.outputs.branch }}"
          echo "GITHUB REF: ${GITHUB_REF}"

      - name: Deploy for review
        if: ${{ contains(github.event.comment.body, '/review') }}
        run: |
          git fetch --unshallow
          git checkout deploy/review
          git pull
          git merge --no-ff --no-edit ${{ steps.workflow-vars.outputs.sha }} -m "Merge ${{ steps.workflow-vars.outputs.sha }} into deploy/review"
